/* Curated list of 25 real, well-known board/card/party games.
 * minPlayers/maxPlayers and minTime/maxTime (minutes) reflect the ranges
 * commonly printed on each game's box / publisher listing. These are
 * typical ranges, not guarantees — actual playtime varies by group.
 */
var GAMES = [
  { name: 'Catan', minPlayers: 3, maxPlayers: 4, minTime: 60, maxTime: 90,
    description: 'Trade resources and build settlements, roads, and cities across an island.' },
  { name: 'Ticket to Ride', minPlayers: 2, maxPlayers: 5, minTime: 30, maxTime: 60,
    description: 'Collect train cards and claim railway routes across a map to connect cities.' },
  { name: 'Codenames', minPlayers: 2, maxPlayers: 8, minTime: 15, maxTime: 30,
    description: 'Two teams race to guess their agents on the board from one-word clues.' },
  { name: 'Pandemic', minPlayers: 2, maxPlayers: 4, minTime: 45, maxTime: 60,
    description: 'Cooperative game where players work together to stop four diseases from spreading worldwide.' },
  { name: 'Splendor', minPlayers: 2, maxPlayers: 4, minTime: 20, maxTime: 30,
    description: 'Collect gem tokens to buy development cards and build an engine of discounts.' },
  { name: 'Azul', minPlayers: 2, maxPlayers: 4, minTime: 30, maxTime: 45,
    description: 'Draft colorful tiles to decorate a Portuguese palace wall without wasting pieces.' },
  { name: 'Carcassonne', minPlayers: 2, maxPlayers: 5, minTime: 30, maxTime: 45,
    description: 'Lay tiles to build a medieval landscape of cities, roads, and cloisters.' },
  { name: '7 Wonders', minPlayers: 2, maxPlayers: 7, minTime: 30, maxTime: 45,
    description: 'Draft cards over three ages to develop an ancient civilization and its wonder.' },
  { name: 'Dixit', minPlayers: 3, maxPlayers: 6, minTime: 30, maxTime: 30,
    description: 'Storytelling game where players match dreamlike cards to a clue phrase.' },
  { name: 'Wingspan', minPlayers: 1, maxPlayers: 5, minTime: 40, maxTime: 70,
    description: 'Attract birds to your wildlife preserves in this engine-building card game.' },
  { name: 'King of Tokyo', minPlayers: 2, maxPlayers: 6, minTime: 30, maxTime: 30,
    description: 'Giant monsters roll dice to battle for control of Tokyo.' },
  { name: 'Sushi Go!', minPlayers: 2, maxPlayers: 5, minTime: 15, maxTime: 15,
    description: 'Fast-paced card drafting game where you pick the best combo of sushi dishes.' },
  { name: 'Love Letter', minPlayers: 2, maxPlayers: 4, minTime: 15, maxTime: 20,
    description: 'Tiny deduction card game about getting a letter to the princess.' },
  { name: 'Coup', minPlayers: 2, maxPlayers: 6, minTime: 15, maxTime: 15,
    description: 'Bluffing card game of influence, betrayal, and elimination in a dystopian court.' },
  { name: 'Bang!', minPlayers: 4, maxPlayers: 7, minTime: 20, maxTime: 40,
    description: 'Wild-west card game of hidden roles: sheriff, deputies, outlaws, and a renegade.' },
  { name: 'Sagrada', minPlayers: 1, maxPlayers: 4, minTime: 30, maxTime: 45,
    description: 'Draft dice to build a stained-glass window following color and shade rules.' },
  { name: 'Terraforming Mars', minPlayers: 1, maxPlayers: 5, minTime: 90, maxTime: 120,
    description: 'Heavy strategy game about corporations racing to terraform Mars over generations.' },
  { name: 'Scythe', minPlayers: 1, maxPlayers: 5, minTime: 90, maxTime: 115,
    description: 'Area-control strategy game of competing factions in an alternate-1920s Europe.' },
  { name: 'Clue', minPlayers: 2, maxPlayers: 6, minTime: 30, maxTime: 45,
    description: 'Classic deduction game: figure out who committed the murder, with what, and where.' },
  { name: 'Uno', minPlayers: 2, maxPlayers: 10, minTime: 15, maxTime: 30,
    description: 'Classic card game of matching colors and numbers, with action cards to disrupt opponents.' },
  { name: 'Exploding Kittens', minPlayers: 2, maxPlayers: 5, minTime: 15, maxTime: 15,
    description: 'Draw cards and avoid the exploding kitten in this fast, silly party card game.' },
  { name: 'The Resistance: Avalon', minPlayers: 5, maxPlayers: 10, minTime: 30, maxTime: 30,
    description: 'Social deduction game of loyal servants of Arthur versus hidden minions of Mordred.' },
  { name: 'One Night Ultimate Werewolf', minPlayers: 3, maxPlayers: 10, minTime: 10, maxTime: 10,
    description: 'Fast single-round social deduction game — find the werewolves before time runs out.' },
  { name: 'Bohnanza', minPlayers: 2, maxPlayers: 7, minTime: 45, maxTime: 45,
    description: 'Trade and plant bean cards to build the most valuable bean fields.' },
  { name: 'Forbidden Island', minPlayers: 2, maxPlayers: 4, minTime: 30, maxTime: 45,
    description: 'Cooperative game to recover four treasures before a sinking island claims them.' }
];
