// Curated riddle bank — roughly two months' worth (60) so the daily pick
// doesn't repeat too fast. Each entry is { q: riddle text, a: answer }.
var RIDDLES = [
  { q: "What has keys but can't open a single lock?", a: "A keyboard." },
  { q: "What has a face and two hands but no arms or legs?", a: "A clock." },
  { q: "What gets wetter the more it dries?", a: "A towel." },
  { q: "What has to be broken before you can use it?", a: "An egg." },
  { q: "I speak without a mouth and hear without ears. I have no body, but I come alive with the wind. What am I?", a: "An echo." },
  { q: "The more you take, the more you leave behind. What am I?", a: "Footsteps." },
  { q: "I have cities, but no houses. I have mountains, but no trees. I have water, but no fish. What am I?", a: "A map." },
  { q: "What has a head and a tail but no body?", a: "A coin." },
  { q: "I follow you all day but disappear at night. What am I?", a: "Your shadow." },
  { q: "I always point the way but never leave my spot, and I name four friends: north, south, east, and west. What am I?", a: "A compass." },
  { q: "The more of me there is, the less you see. What am I?", a: "Darkness." },
  { q: "What has many pages but is not a book, and can be filled with words yet has no story?", a: "A dictionary." },
  { q: "I get shorter as I work harder. What am I?", a: "A candle." },
  { q: "What has words but never speaks?", a: "A book." },
  { q: "The more you sharpen me, the shorter I get. What am I?", a: "A pencil." },
  { q: "What can travel around the world while staying in a corner?", a: "A stamp." },
  { q: "What gets bigger the more you take away from it?", a: "A hole." },
  { q: "I show you a world that isn't quite real, but I never lie about what's in front of me. What am I?", a: "A mirror." },
  { q: "What can you hold without ever touching it?", a: "Your breath." },
  { q: "What five-letter word becomes shorter when you add two letters to it?", a: "\"Short\" — adding \"er\" makes \"shorter.\"" },
  { q: "What has branches but no leaves, trunk, or fruit?", a: "A bank (or a family tree)." },
  { q: "What has 88 keys but can't open a single door?", a: "A piano." },
  { q: "What has an eye but cannot see?", a: "A needle." },
  { q: "What always has five fingers but is never alive?", a: "A glove." },
  { q: "What goes up and down but never actually moves?", a: "A staircase." },
  { q: "I can be caught but never thrown. What am I?", a: "A cold." },
  { q: "What falls but never gets hurt?", a: "Rain." },
  { q: "What has colors but no paint, and appears after rain but is never wet?", a: "A rainbow." },
  { q: "What melts away without ever being warm?", a: "Ice." },
  { q: "What has 12 months but only one page missing on any given day?", a: "A calendar." },
  { q: "I'm told after I'm made, kept after I'm told, but I'm broken the moment I'm known. What am I?", a: "A secret." },
  { q: "What can be broken, yet never held?", a: "A promise." },
  { q: "What can fill a room but takes up no space?", a: "Silence." },
  { q: "What has holes all over but still holds water?", a: "A sponge." },
  { q: "What is full of holes but still catches things?", a: "A net." },
  { q: "What has teeth but cannot bite?", a: "A comb." },
  { q: "What grows in rows and wears its own coat, but has no arms to wear it with?", a: "An ear of corn." },
  { q: "What sits on your nose and in front of your eyes but never actually gets in the way?", a: "Glasses." },
  { q: "What has a skin but no flesh, bones, or blood, yet is round and juicy inside?", a: "An orange." },
  { q: "What makes you cry without hurting your feelings?", a: "An onion." },
  { q: "What has a head, catches fire, but is not a person?", a: "A match." },
  { q: "What can be full of holes and still hold water?", a: "A well." },
  { q: "What gets darker the more layers you add, and dries the same color it started?", a: "A coat of paint." },
  { q: "What has hinges but is not alive?", a: "A door." },
  { q: "What has panes but feels no pain?", a: "A window." },
  { q: "What runs but never walks, has a bank but no money, and a mouth but never talks?", a: "A river." },
  { q: "What twinkles at night but disappears by morning?", a: "A star." },
  { q: "What comes once in a minute, twice in a moment, but never in a thousand years?", a: "The letter \"M.\"" },
  { q: "What is always coming but never actually arrives?", a: "Tomorrow." },
  { q: "What belongs to you, but other people use it more than you do?", a: "Your name." },
  { q: "What melts in the sun and is built one scoop or one snowball at a time?", a: "A snowman." },
  { q: "What rises and falls without ever standing up?", a: "A wave." },
  { q: "What surrounds a valley, has no voice, but repeats everything you say?", a: "A canyon (echo off canyon walls)." },
  { q: "What rolls in overnight, hides the horizon, and vanishes once the sun gets high enough?", a: "Fog." },
  { q: "What opens up when it rains and closes when it shines?", a: "An umbrella." },
  { q: "What has teeth that grip everything but never chews?", a: "A zipper." },
  { q: "What kind of band never plays a single note of music?", a: "A rubber band." },
  { q: "What rises with heat and falls with cold, but never actually moves on its own?", a: "The line in a thermometer." },
  { q: "What writes in white but is not a pen, and disappears the moment you wipe it away?", a: "Chalk." },
  { q: "What connects two towns, carries traffic every day, but never itself moves an inch?", a: "A road." },
  { q: "What connects two sides without ever taking a single step?", a: "A bridge." },
];
