// Small Space Workouts — curated exercise library.
// 15 real, well-known bodyweight exercises, all explicitly chosen to work
// in a small apartment: no jumping, no equipment (a sturdy chair is used by
// 2 of them, which is standard household furniture, not gym gear), and low
// enough impact/noise to not disturb downstairs neighbors.

const EXERCISES = [
  {
    id: "wall-sit",
    name: "Wall Sit",
    muscleGroup: "Legs / Quads",
    difficulty: "beginner",
    type: "hold",
    defaultSeconds: 30,
    instructions: "Stand with your back flat against a wall, feet shoulder-width apart and about two feet from the wall. Slide down until your knees form roughly a 90-degree angle, like sitting in an invisible chair. Hold the position, keeping your back pressed flat against the wall and your core engaged.",
    quietNote: "Fully silent, zero floor impact.",
  },
  {
    id: "forearm-plank",
    name: "Forearm Plank",
    muscleGroup: "Core",
    difficulty: "beginner",
    type: "hold",
    defaultSeconds: 30,
    instructions: "Rest on your forearms and toes, elbows under your shoulders, body forming a straight line from head to heels. Keep your hips level — don't let them sag or pike up. Squeeze your core and glutes throughout.",
    quietNote: "Silent, done flat on a mat.",
  },
  {
    id: "glute-bridge-hold",
    name: "Glute Bridge Hold",
    muscleGroup: "Glutes / Hamstrings",
    difficulty: "beginner",
    type: "hold",
    defaultSeconds: 30,
    instructions: "Lie on your back, knees bent, feet flat on the floor hip-width apart. Push through your heels to lift your hips until your body forms a straight line from shoulders to knees. Squeeze your glutes at the top and hold.",
    quietNote: "Silent, done lying on a mat.",
  },
  {
    id: "slow-squat",
    name: "Slow-Tempo Bodyweight Squat",
    muscleGroup: "Quads / Glutes",
    difficulty: "beginner",
    type: "reps",
    defaultReps: 12,
    instructions: "Stand with feet shoulder-width apart. Lower yourself over 3 slow seconds as if sitting into a chair, keeping your chest up and knees tracking over your toes. Pause briefly at the bottom, then rise over 3 slow seconds. The slow tempo builds strength without any impact.",
    quietNote: "No jumping, controlled tempo keeps it quiet.",
  },
  {
    id: "standing-march",
    name: "Standing Marching in Place",
    muscleGroup: "Cardio / Core",
    difficulty: "beginner",
    type: "hold",
    defaultSeconds: 45,
    instructions: "Stand tall and lift one knee toward your hip at a time, alternating sides at a steady, controlled pace — like marching, not running. Pump your arms gently for extra intensity. Keep your foot placement soft to stay quiet.",
    quietNote: "A quiet cardio alternative to jumping jacks — land softly on the balls of your feet.",
  },
  {
    id: "dead-bug",
    name: "Dead Bug",
    muscleGroup: "Core",
    difficulty: "beginner",
    type: "reps",
    defaultReps: 10,
    instructions: "Lie on your back with arms extended toward the ceiling and knees bent at 90 degrees above your hips. Slowly lower one arm and the opposite leg toward the floor without letting your lower back arch, then return to start. Alternate sides.",
    quietNote: "Silent, done lying on a mat.",
  },
  {
    id: "superman-hold",
    name: "Superman Hold",
    muscleGroup: "Lower Back / Glutes",
    difficulty: "intermediate",
    type: "hold",
    defaultSeconds: 25,
    instructions: "Lie face down with arms extended in front of you. Simultaneously lift your arms, chest, and legs a few inches off the floor, keeping your neck neutral. Hold, squeezing your lower back and glutes.",
    quietNote: "Silent, done lying on a mat.",
  },
  {
    id: "bird-dog",
    name: "Bird Dog",
    muscleGroup: "Core / Balance",
    difficulty: "intermediate",
    type: "reps",
    defaultReps: 10,
    instructions: "Start on hands and knees, wrists under shoulders, knees under hips. Extend one arm forward and the opposite leg back simultaneously, keeping your hips and shoulders square. Hold briefly, then return and switch sides.",
    quietNote: "Silent, done on a mat.",
  },
  {
    id: "slow-calf-raises",
    name: "Slow Calf Raises",
    muscleGroup: "Calves",
    difficulty: "intermediate",
    type: "reps",
    defaultReps: 15,
    instructions: "Stand tall, feet hip-width apart, holding onto a wall or chair for balance if needed. Rise slowly onto the balls of your feet over 2 seconds, pause, then lower slowly over 2 seconds. Stay controlled to keep it quiet.",
    quietNote: "Stay on the balls of your feet and control the descent to avoid any heel-drop noise.",
  },
  {
    id: "incline-pushup",
    name: "Incline / Standard Push-Up",
    muscleGroup: "Chest / Shoulders / Triceps",
    difficulty: "intermediate",
    type: "reps",
    defaultReps: 10,
    instructions: "Place hands slightly wider than shoulder-width on the floor (or on a sturdy countertop/table edge for an easier incline version). Lower your chest toward your hands with elbows at about 45 degrees, then push back up. Keep your body in a straight line throughout.",
    quietNote: "Silent — no impact, control the lowering phase.",
  },
  {
    id: "side-plank",
    name: "Side Plank",
    muscleGroup: "Obliques / Core",
    difficulty: "intermediate",
    type: "hold",
    defaultSeconds: 20,
    instructions: "Lie on your side, propped up on one forearm with elbow under your shoulder. Stack your feet and lift your hips until your body forms a straight line. Hold, then repeat on the other side.",
    quietNote: "Silent, done on a mat.",
  },
  {
    id: "chair-tricep-dips",
    name: "Chair Tricep Dips",
    muscleGroup: "Triceps / Shoulders",
    difficulty: "intermediate",
    type: "reps",
    defaultReps: 10,
    instructions: "Sit on the edge of a sturdy chair, hands gripping the edge beside your hips, legs extended out in front. Slide off the seat and lower your body by bending your elbows to about 90 degrees, then push back up.",
    quietNote: "Silent — make sure the chair is stable and won't slide.",
  },
  {
    id: "bulgarian-split-squat",
    name: "Bulgarian Split Squat (Chair-Assisted)",
    muscleGroup: "Quads / Glutes",
    difficulty: "advanced",
    type: "reps",
    defaultReps: 8,
    instructions: "Stand a couple of feet in front of a sturdy chair, facing away from it, and rest the top of one foot on the seat behind you. Lower your back knee toward the floor by bending your front leg, then push back up through your front heel. Complete all reps on one side before switching.",
    quietNote: "No impact — control the descent for balance and quiet.",
  },
  {
    id: "slow-mountain-climbers",
    name: "Slow Mountain Climbers",
    muscleGroup: "Core / Cardio",
    difficulty: "advanced",
    type: "hold",
    defaultSeconds: 30,
    instructions: "Start in a high plank position, hands under shoulders. Slowly drive one knee toward your chest, then return it and switch legs, keeping hips low and controlled — a deliberate, unhurried pace rather than a fast running motion.",
    quietNote: "Keep the tempo slow and feet sliding softly rather than stomping — no jumping involved.",
  },
  {
    id: "plank-shoulder-taps",
    name: "Plank Shoulder Taps",
    muscleGroup: "Core / Shoulders",
    difficulty: "advanced",
    type: "reps",
    defaultReps: 16,
    instructions: "Start in a high plank position with feet a bit wider than usual for stability. Without rocking your hips, lift one hand to tap the opposite shoulder, then place it back down and repeat with the other hand. Keep your core braced throughout.",
    quietNote: "Silent, done on a mat.",
  },
];

if (typeof module !== "undefined" && module.exports) {
  module.exports = { EXERCISES };
}
