/* Curated sales tips — 30 short, genuinely useful daily lessons.
   Categories: pitching, objections, closing, follow-up, listening.
   Each tip is written to be read in under 20 seconds. */

const SALES_TIPS = [
  { id: 1, category: "Pitching", title: "Lead with the problem, not the product", body: "Open by naming the exact problem your buyer has, in their words. People lean in when they hear their own pain described accurately — the product can wait until they're already nodding." },
  { id: 2, category: "Listening", title: "Count to two before you respond", body: "After a prospect finishes talking, silently count 'one, two' before replying. It stops you from interrupting mid-thought and often the prospect adds one more sentence that's more honest than the first." },
  { id: 3, category: "Objections", title: "Repeat the objection back before answering", body: "\"So the concern is the price feels high relative to what you're currently paying?\" Restating shows you actually heard it, and half the time the prospect softens the objection themselves while confirming it." },
  { id: 4, category: "Closing", title: "Ask for the next step, not the sale", body: "Instead of \"are you ready to buy,\" ask \"what would need to be true for this to move forward?\" It gets you the real blockers instead of a polite no or a vague maybe." },
  { id: 5, category: "Follow-up", title: "Follow up with value, not a check-in", body: "\"Just checking in\" gives the prospect nothing to respond to. Send a relevant article, a case study, or an answer to something they mentioned — give them a reason to reply." },
  { id: 6, category: "Pitching", title: "Cut your pitch in half", body: "Time yourself. Whatever your standard pitch length is, try telling it in half the time. You'll cut the filler and keep the parts that actually move the conversation forward." },
  { id: 7, category: "Objections", title: "\"Not interested\" is rarely the real objection", body: "It usually means \"I don't see how this applies to me yet\" or \"I'm busy.\" Ask one curious follow-up question before you let the conversation end — you'll often surface the real reason." },
  { id: 8, category: "Closing", title: "Silence after the price is a tool, not a mistake", body: "State your price and stop talking. The urge to fill the silence with a discount or justification is strong — resist it. Let the prospect speak first." },
  { id: 9, category: "Listening", title: "Take notes in the prospect's exact words", body: "When you write down their phrasing instead of paraphrasing, you can mirror it back later in your proposal or follow-up. It reads as \"this person really understood us.\"" },
  { id: 10, category: "Follow-up", title: "The third touch converts more than the first", body: "Most reps give up after one unanswered email. Buyers are busy, not uninterested — a short, polite third follow-up is often the one that gets a reply." },
  { id: 11, category: "Pitching", title: "Ask a question before you pitch anything", body: "\"What made you take this call today?\" tells you what to emphasize and what to skip. A pitch tailored to a stated need beats a polished generic one every time." },
  { id: 12, category: "Objections", title: "Separate the objection from the emotion behind it", body: "\"Too expensive\" can mean the budget genuinely isn't there, or it can mean they're not yet convinced of the value. Ask which one it is before you negotiate on price." },
  { id: 13, category: "Closing", title: "Give a deadline that's real, not manufactured", body: "Fake urgency (\"price goes up tomorrow\" when it doesn't) erodes trust fast. If there's a genuine reason to decide soon, state it plainly — genuine urgency still works." },
  { id: 14, category: "Listening", title: "Notice what they don't say", body: "If a prospect describes their current process in detail but skips over budget or timeline, that's worth a direct question. Gaps in what people volunteer are often where the real hesitation lives." },
  { id: 15, category: "Follow-up", title: "Summarize the call in your follow-up email", body: "A short recap of what was discussed and agreed shows professionalism and gives the prospect an easy way to correct anything you misunderstood before it becomes a problem." },
  { id: 16, category: "Pitching", title: "Talk in outcomes, not features", body: "\"Saves your team six hours a week\" lands harder than \"has an automation module.\" Translate every feature into what changes for the person listening." },
  { id: 17, category: "Objections", title: "\"I need to think about it\" needs a specific follow-up question", body: "Ask \"what part specifically do you want to think through?\" Vague hesitation becomes a concrete question you can actually address on the spot." },
  { id: 18, category: "Closing", title: "Make the next step small and specific", body: "\"Let's schedule 15 minutes with your ops lead next Tuesday\" is easier to say yes to than \"let's keep in touch.\" Vague next steps are where deals quietly die." },
  { id: 19, category: "Listening", title: "Ask \"what else\" one more time than feels natural", body: "The first answer to \"what's frustrating about your current setup\" is often the safe one. A second \"what else\" frequently surfaces the real driver behind the purchase." },
  { id: 20, category: "Follow-up", title: "Match your follow-up speed to their urgency, not yours", body: "If a prospect took two weeks to reply, don't panic-follow-up daily. If they replied in ten minutes, don't sit on your response for two days. Mirror their pace." },
  { id: 21, category: "Pitching", title: "Know the one sentence you'd keep if you could only say one", body: "If you had to cut your pitch to a single sentence, what would it be? Lead with that sentence, then let the rest of the pitch support it instead of burying it." },
  { id: 22, category: "Objections", title: "Don't argue with a competitor comparison — ask about it", body: "If they mention a competitor, resist the urge to trash it. Ask \"what do you like about them so far?\" You'll learn what actually matters to the buyer, unfiltered." },
  { id: 23, category: "Closing", title: "Reconfirm the pain before you ask for the close", body: "Right before asking for commitment, restate the cost of doing nothing: \"so without this, the team keeps losing X hours a week.\" It reconnects the decision to the original reason it matters." },
  { id: 24, category: "Listening", title: "Let them describe success in their own terms", body: "Ask \"what does this looking successful in six months look like?\" Their answer tells you exactly what to reference when you check in later and what to measure the deal against." },
  { id: 25, category: "Follow-up", title: "A no today isn't a no forever — ask when to check back", body: "If timing is the real blocker, ask directly: \"when would be a better time to revisit this?\" Most prospects will give you an honest answer, and now you have a reason to reach out later." },
  { id: 26, category: "Pitching", title: "Use a customer's exact words in your next pitch", body: "When a happy customer describes a benefit in a memorable way, write it down. Their phrasing, used carefully, often resonates more than anything your marketing team wrote." },
  { id: 27, category: "Objections", title: "Price objections often mean value hasn't landed yet", body: "Before discounting, ask yourself whether you've clearly connected the price to a specific, quantified outcome. Often the fix is a sharper pitch, not a lower number." },
  { id: 28, category: "Closing", title: "Ask permission before you push for a decision", body: "\"Is it okay if I ask you directly where your head's at on this?\" This small framing makes a direct ask feel respectful instead of pushy, and prospects usually answer honestly." },
  { id: 29, category: "Listening", title: "Watch for a change in energy, not just words", body: "A prospect who suddenly speaks faster or slower, or gets quieter, is reacting to something real. Pause and ask what just came to mind — you'll often learn more than from the words alone." },
  { id: 30, category: "Follow-up", title: "Keep a running list of every 'not now' and why", body: "Log the stated reason each time a deal stalls. Patterns across many \"not now\"s reveal whether it's a timing issue, a pricing issue, or a positioning issue you can actually fix." },
];

if (typeof module !== "undefined" && module.exports) {
  module.exports = { SALES_TIPS };
}
